### ISSUE TITLE
android.fg FC due to missing resource

### ISSUE THREAD

**Issue by rafifos** [FlymeOS/devices-base_cm#12]
from logcat:

> 03-27 08:10:56.812  1767  1830 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: android.fg
> 03-27 08:10:56.812  1767  1830 E AndroidRuntime: android.content.res.Resources$NotFoundException: String array resource ID #0x0
> 03-27 08:10:56.812  1767  1830 E AndroidRuntime: 	at android.content.res.Resources.getStringArray(Resources.java:569)
> 03-27 08:10:56.812  1767  1830 E AndroidRuntime: 	at org.cyanogenmod.internal.util.QSUtils.translateDynamicQsTileSpecToIndex(QSUtils.java:188)
> 03-27 08:10:56.812  1767  1830 E AndroidRuntime: 	at org.cyanogenmod.internal.util.QSUtils.getDynamicQSTileResIconId(QSUtils.java:153)
> 03-27 08:10:56.812  1767  1830 E AndroidRuntime: 	at com.android.server.usb.UsbDeviceManager$UsbHandler.publishAdbCustomTile(UsbDeviceManager.java:935)
> 03-27 08:10:56.812  1767  1830 E AndroidRuntime: 	at com.android.server.usb.UsbDeviceManager$UsbHandler.updateAdbNotification(UsbDeviceManager.java:895)
> 03-27 08:10:56.812  1767  1830 E AndroidRuntime: 	at com.android.server.usb.UsbDeviceManager$UsbHandler.handleMessage(UsbDeviceManager.java:735)
> 03-27 08:10:56.812  1767  1830 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
> 03-27 08:10:56.812  1767  1830 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
> 03-27 08:10:56.812  1767  1830 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:61)
> 03-27 08:10:56.812  1767  1830 E AndroidRuntime: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)

**Comment by hexiaoshuai** [comment]
https://github.com/FlymeOS/devices-base_cm/commit/e6bd4a4131c27e56a99667eb78882155fb1c9b56

**Comment by rafifos** [comment]
I'm on the lastest patch... :/

**Comment by rafifos** [comment]
I will try to sync everything again at a later time, i'm changing my isp now, and I only have 100mb/day on mobile data

**Comment by rafifos** [comment]
I've verified my patch, the commit is there.. weird

**Comment by rafifos** [comment]
Closed, see https://github.com/FlymeOS/devices-base_cm/issues/11
