### ISSUE TITLE
[Low priority?] Missing fonts in /system/fonts

### ISSUE THREAD

**Issue by rafifos** [FlymeOS/devices-base_cm#14]
from logcat:

> 03-27 08:00:23.078   291   291 E Minikin : addFont failed to create font /system/fonts/Padauk.ttf
> 03-27 08:00:23.100   291   291 E Minikin : addFont failed to create font /system/fonts/NanumGothic.ttf
> 03-27 08:00:23.100   291   291 E Minikin : addFont failed to create font /system/fonts/DroidSansFallback.ttf
> 03-27 08:00:23.100   291   291 E Minikin : addFont failed to create font /system/fonts/MTLmr3m.ttf

**Comment by lucalves** [comment]
Download the font's and copy to the directory system/fonts.

@rafifos

**Comment by rafifos** [comment]
This project is long dead, I haven't ported any roms to it since 2017 too.

Time to close this issue, lol.
