### ISSUE TITLE
SystemUI crashing after boot (Activity Manager?)

### ISSUE THREAD

**Issue by Lyuu17** [FlymeOS/devices-base_cm#18]
`08-11 01:54:05.439  3454  6575 E ActivityManager: Activity Manager Crash
08-11 01:54:05.439  3454  6575 E ActivityManager: java.lang.IllegalArgumentException: Unknown service start result: -1
08-11 01:54:05.439  3454  6575 E ActivityManager: 	at com.android.server.am.ActiveServices.serviceDoneExecutingLocked(ActiveServices.java:2005)
08-11 01:54:05.439  3454  6575 E ActivityManager: 	at com.android.server.am.ActivityManagerService.serviceDoneExecuting(ActivityManagerService.java:16500)
08-11 01:54:05.439  3454  6575 E ActivityManager: 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:1046)
08-11 01:54:05.439  3454  6575 E ActivityManager: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2682)
08-11 01:54:05.439  3454  6575 E ActivityManager: 	at com.android.server.am.FlymeExtActivityManagerService.onTransact(FlymeExtActivityManagerService.java)
08-11 01:54:05.439  3454  6575 E ActivityManager: 	at android.os.Binder.execTransact(Binder.java:453)
08-11 01:54:05.439  7226  7226 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:-1 android.content.ContextWrapper.startService:587 android.content.ContextWrapper.startService:587 com.meizu.safe.service.MzSecMainService.a:83 com.meizu.safe.blockService.service.BootReceiver.a:26 
08-11 01:54:05.441  3454  6575 E ActivityManager: Service done with onDestroy, but executeNesting=2: ServiceRecord{2578a56 u0 com.meizu.safe/.blockService.service.SDKUpdateService}
08-11 01:54:05.441  3454  6575 E ActivityManager: android.util.Log$TerribleFailure: Service done with onDestroy, but executeNesting=2: ServiceRecord{2578a56 u0 com.meizu.safe/.blockService.service.SDKUpdateService}
08-11 01:54:05.441  3454  6575 E ActivityManager: 	at android.util.Log.wtf(Log.java:291)
08-11 01:54:05.441  3454  6575 E ActivityManager: 	at android.util.Slog.wtfStack(Slog.java:98)
08-11 01:54:05.441  3454  6575 E ActivityManager: 	at com.android.server.am.ActiveServices.serviceDoneExecutingLocked(ActiveServices.java:2021)
08-11 01:54:05.441  3454  6575 E ActivityManager: 	at com.android.server.am.ActivityManagerService.serviceDoneExecuting(ActivityManagerService.java:16500)
08-11 01:54:05.441  3454  6575 E ActivityManager: 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:1046)
08-11 01:54:05.441  3454  6575 E ActivityManager: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2682)
08-11 01:54:05.441  3454  6575 E ActivityManager: 	at com.android.server.am.FlymeExtActivityManagerService.onTransact(FlymeExtActivityManagerService.java)
08-11 01:54:05.441  3454  6575 E ActivityManager: 	at android.os.Binder.execTransact(Binder.java:453)`

[log.txt](https://github.com/FlymeOS/devices-base_cm/files/1216768/log.txt)

**Comment by hexiaoshuai** [comment]
The next update will be fix

**Comment by Lyuu17** [comment]
Ok, thanks so much!
