### ISSUE TITLE
Flyme 6?

### ISSUE THREAD

**Issue by rafifos** [FlymeOS/devices-base_cm#6]
I'm not here to ask any ETA, but I have to ask, can we expect this repo to be updated to Flyme 6 patchrom?

**Comment by lfelipehdezlopez** [comment]
I was wondering the same thing. Are we getting flyme cm based or LOS based?

**Comment by zoujunhua** [comment]
The "base_cm" which based on the cm/los is under development.
It will be on the line at the end of June.

**Comment by rorre** [comment]
Whoa~ good a reply!
Ok thanks for the information.

Pada tanggal 19 Mei 2017 16.54, "zoujunhua" <notifications@github.com>
menulis:
