### ISSUE TITLE
为什么 还是基于cm12的不更新吗?

### ISSUE THREAD

**Issue by 935713827** [FlymeOS/devices-base_cm#7]
Flyme 6 不是早更新了吗   6.0   这个base_cm 不应该也更新一下 我看还算12.1的....
难道说 6.0  CM 还是可以用这个 基于cm 12.1的 所以不更新????

**Comment by zoujunhua** [comment]
基于安卓6.0的base_cm正在开发中，将于６月底上线

**Comment by 935713827** [comment]
Thank you  感谢你的回复
