### ISSUE TITLE
说好的Los base呢，人与人之间的信任呢？

### ISSUE THREAD

**Issue by 935713827** [FlymeOS/devices-base_cm#8]
![168152b6-32ee-4433-bf3f-fc07d28aa07d](https://user-images.githubusercontent.com/13399243/27850223-ae2db850-6185-11e7-8c93-200a6aa60a09.png)

**Comment by crabkun** [comment]
哈哈哈我也是等了挺久的

**Comment by zoujunhua** [comment]
在修复其他问题时耽误了base_cm的问题修复，会尽快上线

**Comment by cl111c** [comment]
base7.0呢

**Comment by zoujunhua** [comment]
android n在开发中，请耐心等待。
